version: "3.2"
services:
  backend:
    build: 
      context: "backend"
      args:
        TZ: ${TZ}
    restart: always
    volumes:
      - ./backend/:/src
      - ./alertmanager:/alertmanager
      - ./frontend/labyrinth/public:/public
    networks:
      - labyrinth
    environment: 
      REDIS_HOST: redis
      PRODUCTION: 1
 
  frontend:
    image: nginx:latest
    restart: always
    depends_on:
      - lego
    networks:
      - labyrinth
    user: ${CURRENT_UID}
    command: /entrypoint.sh
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx:/nginx
        - ./frontend/labyrinth/dist/:/dist:ro
        - ./nginx/entrypoint.sh:/entrypoint.sh
        - ./nginx/watch.sh:/watch.sh
    environment:
        COMPOSE_CONVERT_WINDOWS_PATHS: 1
    healthcheck:
        test: curl -k -f https://localhost/insecure || service nginx restart
        interval: 20s
        timeout: 10s
        retries: 3
    ports:
        - "443:443"

 


  lego:
    build: nginx
    restart: always
    volumes:
      - ./nginx:/nginx
      - ./nginx/lego.sh:/lego.sh
    env_file: 
      - nginx/.env


networks:
  labyrinth:
    external: true
