version: "3.2"
services:
  backend:
    build: 
      context: "backend"
      args:
        TZ: ${TZ}
    restart: always
    volumes:
      - ./backend/:/src
      - ./alertmanager:/alertmanager
    networks:
      - labyrinth
    environment: 
      MONGO_USERNAME: root
      MONGO_PASSWORD: temp
      MONGO_HOST: mongo
      REDIS_HOST: redis
      PRODUCTION: 1
 
  frontend:
    image: nginx:latest
    restart: always
    depends_on:
      - lego
    networks:
      - labyrinth
    user: ${CURRENT_UID}
    command: /entrypoint.sh
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx:/nginx
        - ./frontend/labyrinth/dist/:/dist
        - ./nginx/entrypoint.sh:/entrypoint.sh
        - ./nginx/watch.sh:/watch.sh
    environment:
        COMPOSE_CONVERT_WINDOWS_PATHS: 1
    healthcheck:
        test: curl -k -f https://localhost/insecure || service nginx restart
        interval: 20s
        timeout: 10s
        retries: 3
    ports:
        - "443:443"

 


  lego:
    build: nginx
    restart: always
    volumes:
      - ./nginx:/nginx
      - ./nginx/lego.sh:/lego.sh
    env_file: 
      - nginx/.env


  # Mongo
  mongo:
    image: mongo
    restart: always
    networks:
      - labyrinth
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: temp

  
  # Redis
  redis:
    image: bitnami/redis:latest
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - labyrinth
    # volumes:
    #  - ./redis_data:/bitnami/redis/data

  alertmanager:
    build: 
      context: alertmanager
      args:
        TZ: ${TZ}
    restart: always
    networks:
      - labyrinth
    volumes:
      - ./alertmanager:/src

      
  # Scanner and Watcher Cron
  samplecron:
    build: 
      context: "cron"
      args:
        TZ: ${TZ}    
    restart: always
    volumes:
      - ./backend/:/src
      - ./cron:/cron
      - ./alertmanager:/alertmanager
    networks:
      - labyrinth
    environment: 
      MONGO_USERNAME: root
      MONGO_PASSWORD: temp
      MONGO_HOST: mongo
      REDIS_HOST: redis

networks:
  labyrinth:
    external: true
