version: "3.2"
services:
  devel:
    environment:
      COMPOSE_CONVERT_WINDOWS_PATHS: 1
      CHOKIDAR_USEPOLLING: "true"

    build: ./frontend
    ports:
      - "8100:8000"
      - "8101:8080"
    volumes:
      - ./frontend:/src
      - /src/labyrinth/node_modules
  