[pytest]
testpaths = test
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = --strict-markers
norecursedirs = htmlcov __pycache__ .pytest_cache .git uploads samples snippets templates ai common
