name: Labyrinth Backend Tests
on: push
jobs:
  env:
    GITHUB: 1
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Start custom docker network
        run: docker network create labyrinth || true
        
      - name: Bring up dockers
        run: bash start_dev.sh
      
      - name: List Dockers
        run: docker ps
      
      - name: Backend Tests
        run: bash backend/run_tests.sh