name: Labyrinth Frontend Tests
on: push
jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '10'
          cache: 'npm'
          cache-dependency-path: frontend/labyrinth
      
      - name: Install vue
        run: npm install -g @vue/cli

      - name: NPM install
        run: cd frontend/labyrinth && npm install

      - name: Run NPM tests
        run: cd frontend/labyrinth && npm run test:unit
