name: Labyrinth Frontend Tests
on: push
jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '10'
          cache: 'npm'
          cache-dependency-path: frontend/labyrinth
      
      - name: Install vue
        run: npm install -g @vue/cli

      - name: NPM install
        run: cd frontend/labyrinth && npm install

      - name: Run NPM tests
        run: cd frontend/labyrinth && npm run test:unit

      - name: Vue Linting
        run: cd frontend/labyrinth && npm run lint --fix

      - name: Git Config
        run: git pull && git config --local user.email "chet.enright@gmail.com" && git config --local user.name "Automatic Linting"
        
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      
      - name: Commit updated files
        run: git commit -m "Automatic linting fix" -a || true
          
      - name: Push changes
        run: git push